n=input('Word: ')
print(n)
print(n[:-1])
print(n[:-2])
print(n[:-3])
print(n[:-4])
print(n[:-5])
print(n[:-6])
print(n[:-7])
print(n[:-8])
print(n[:-9])
print(n[:-10])
print(n[:-11])
print(n[:-12])
print(n[:-13])
print(n[:-14])
